version: '3.8'

services:
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=test
  #     - POSTGRES_USER=test
  #     - POSTGRES_PASSWORD=test
  #     - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  app:
    build:
      context: .
      dockerfile: ./dockerfile
    expose:
      - 8080
    ports:
      - "3000:3000"
    command:
      - npm start